services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 9000:9000
    networks:
      - inception
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    restart: on-failure


volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/armitite/data/mariadb
      o: bind

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/armitite/data/wordpress
      o: bind

networks:
  inception:
